In [1]:
import pandas as pd

In [2]:
path = '/Users/pandita/Documents/MER_T11_01.csv'
ce = pd.read_csv(path)

# Convert YYYYMM to a datetime format assuming the day is always the first of the month
ce['Date'] = pd.to_datetime(ce['YYYYMM'], format='%Y%m', errors='coerce')

# Drop rows where date conversion failed (if any)
ce = ce.dropna(subset=['Date'])

# Create the pivot table
ce = ce.pivot_table(values='Value', index='Date', columns='Description', aggfunc='first')

# Display the first few rows of the pivot table
ce.reset_index(inplace=True)
ce.head()

Description,Date,Aviation Gasoline CO2 Emissions,"Coal, Including Coal Coke Net Imports, CO2 Emissions","Distillate Fuel Oil, Excluding Biodiesel, CO2 Emissions",Hydrocarbon Gas Liquids CO2 Emissions,Jet Fuel CO2 Emissions,Kerosene CO2 Emissions,Lubricants CO2 Emissions,"Motor Gasoline, Excluding Ethanol, CO2 Emissions","Natural Gas, Excluding Supplemental Gaseous Fuels, CO2 Emissions",Other Petroleum Products CO2 Emissions,Petroleum Coke CO2 Emissions,"Petroleum, Excluding Biofuels, CO2 Emissions",Residual Fuel Oil CO2 Emissions,Total Energy CO2 Emissions
0,1973-01-01,0.428,109.552,55.157,10.463,13.742,5.222,1.037,70.948,125.557,8.754,4.850,218.972,48.370,454.082
1,1973-02-01,0.431,98.833,51.771,8.848,12.193,4.475,1.025,67.422,113.750,7.674,3.992,202.519,44.686,415.102
2,1973-03-01,0.459,98.483,44.460,6.687,12.293,2.582,1.105,75.532,107.700,8.659,4.357,201.245,45.111,407.428
3,1973-04-01,0.446,94.150,33.973,5.793,12.112,2.031,0.979,73.415,97.838,8.230,4.179,176.222,35.063,368.210
4,1973-05-01,0.549,95.424,35.591,5.489,13.756,1.702,1.156,80.105,92.039,8.688,4.645,188.570,36.889,376.032

In [3]:
path1 = '/Users/pandita/Documents/Table_1.2_Primary_Energy_Production_by_Source.xlsx'
ep = pd.read_excel(path1, sheet_name='Monthly Data', skiprows=10)

In [4]:
path2 = '/Users/pandita/Documents/Table_1.3_Primary_Energy_Consumption_by_Source.xlsx'
ec = pd.read_excel(path2, sheet_name='Monthly Data', skiprows=10)

In [5]:
ep['Month'] = pd.to_datetime(ep['Month'], format='%Y%m', errors='coerce')
ec['Month'] = pd.to_datetime(ec['Month'], format='%Y%m', errors='coerce')

In [6]:
merged = pd.merge(ep, ec, on='Month') 
merged = pd.merge(merged, ce, left_on='Month', right_on='Date')

In [7]:
merged = merged.drop(['Month'], axis=1)

pd.set_option('display.max_columns', None)
merged

,Coal Production,Natural Gas (Dry) Production,Crude Oil Production,Natural Gas Plant Liquids Production,Total Fossil Fuels Production,Nuclear Electric Power Production,Hydroelectric Power Production,Geothermal Energy Production,Solar Energy Production,Wind Energy Production,Biomass Energy Production,Total Renewable Energy Production,Total Primary Energy Production,Coal Consumption,Natural Gas Consumption (Excluding Supplemental Gaseous Fuels),Petroleum Consumption (Excluding Biofuels),Total Fossil Fuels Consumption,Nuclear Electric Power Consumption,Hydroelectric Power Consumption,Geothermal Energy Consumption,Solar Energy Consumption,Wind Energy Consumption,Biomass Energy Consumption,Total Renewable Energy Consumption,Total Primary Energy Consumption,Date,Aviation Gasoline CO2 Emissions,"Coal, Including Coal Coke Net Imports, CO2 Emissions","Distillate Fuel Oil, Excluding Biodiesel, CO2 Emissions",Hydrocarbon Gas Liquids CO2 Emissions,Jet Fuel CO2 Emissions,Kerosene CO2 Emissions,Lubricants CO2 Emissions,"Motor Gasoline, Excluding Ethanol, CO2 Emissions","Natural Gas, Excluding Supplemental Gaseous Fuels, CO2 Emissions",Other Petroleum Products CO2 Emissions,Petroleum Coke CO2 Emissions,"Petroleum, Excluding Biofuels, CO2 Emissions",Residual Fuel Oil CO2 Emissions,Total Energy CO2 Emissions
0,1.166486,1.908249,1.649833,0.208064,4.932632,0.068103,0.089562,0.00049,Not Available,Not Available,0.129787,0.219839,5.220574,1.166191,2.397308,3.185268,6.747651,0.068103,0.089562,0.00049,Not Available,Not Available,0.129787,0.219839,7.039731,1973-01-01,0.428,109.552,55.157,10.463,13.742,5.222,1.037,70.948,125.557,8.754,4.850,218.972,48.370,454.082
1,1.086072,1.922543,1.525783,0.195184,4.729582,0.064634,0.079544,0.000448,Not Available,Not Available,0.117338,0.19733,4.991545,1.050588,2.170646,2.941986,6.163095,0.064634,0.079544,0.000448,Not Available,Not Available,0.117338,0.19733,6.428796,1973-02-01,0.431,98.833,51.771,8.848,12.193,4.475,1.025,67.422,113.750,7.674,3.992,202.519,44.686,415.102
2,1.196571,1.86843,1.667094,0.214807,4.946902,0.072494,0.088284,0.000464,Not Available,Not Available,0.129938,0.218686,5.238082,1.046856,2.057315,2.942485,6.044647,0.072494,0.088284,0.000464,Not Available,Not Available,0.129938,0.218686,6.339964,1973-03-01,0.459,98.483,44.460,6.687,12.293,2.582,1.105,75.532,107.700,8.659,4.357,201.245,45.111,407.428
3,1.11223,1.777561,1.616791,0.20969,4.716271,0.06407,0.083152,0.000542,Not Available,Not Available,0.125636,0.20933,4.989672,0.998979,1.873535,2.621315,5.493184,0.06407,0.083152,0.000542,Not Available,Not Available,0.125636,0.20933,5.770589,1973-04-01,0.446,94.150,33.973,5.793,12.112,2.031,0.979,73.415,97.838,8.230,4.179,176.222,35.063,368.210
4,1.216978,1.859241,1.665377,0.215398,4.956995,0.062111,0.085643,0.000505,Not Available,Not Available,0.129834,0.215982,5.235087,1.014502,1.765309,2.836567,5.613551,0.062111,0.085643,0.000505,Not Available,Not Available,0.129834,0.215982,5.895781,1973-05-01,0.549,95.424,35.591,5.489,13.756,1.702,1.156,80.105,92.039,8.688,4.645,188.570,36.889,376.032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,1.051888,3.309225,2.25015,0.688377,7.299641,0.655154,0.07039,0.010065,0.068158,0.151341,0.434435,0.734389,8.689184,0.615143,3.110829,2.990584,6.71453,0.655154,0.07039,0.010065,0.068158,0.151341,0.418218,0.718172,8.096651,2023-03-01,0.135,59.007,53.548,8.721,20.393,0.041,0.397,92.491,162.663,8.899,5.650,193.900,3.625,416.503
603,0.949896,3.19418,2.157078,0.683554,6.984709,0.58925,0.061133,0.009906,0.080494,0.146197,0.40114,0.698869,8.272828,0.495403,2.501283,2.887883,5.883058,0.58925,0.061133,0.009906,0.080494,0.146197,0.388387,0.686116,7.16495,2023-04-01,0.099,47.665,49.292,7.340,19.841,0.124,0.565,89.617,130.477,9.340,5.703,184.407,2.485,363.452
604,0.975419,3.328101,2.236726,0.706581,7.246826,0.641101,0.095479,0.01006,0.090507,0.109319,0.435031,0.740397,8.628324,0.548899,2.392171,3.025771,5.964029,0.641101,0.095479,0.01006,0.090507,0.109319,0.429438,0.734804,7.348888,2023-05-01,0.151,52.595,51.256,6.761,21.243,0.188,0.677,93.490,124.755,9.863,4.266,191.152,3.258,369.434
605,0.954099,3.205094,2.199676,0.699985,7.058854,0.677521,0.066986,0.009549,0.092724,0.093715,0.426737,0.689712,8.426087,0.704001,2.436355,2.97787,6.115871,0.677521,0.066986,0.009549,0.092724,0.093715,0.416358,0.679333,7.47849,2023-06-01,0.146,67.181,49.915,6.588,21.316,0.063,0.643,92.105,127.151,9.478,3.377,187.328,3.697,382.562
606,0.993882,3.33754,2.289102,0.71431,7.334834,0.728858,0.073359,0.009941,0.098239,0.0946,0.434776,0.710915,8.774606,0.914884,2.753936,2.993427,6.659002,0.728858,0.073359,0.009941,0.098239,0.0946,0.415928,0.692067,8.093403,2023-07-01,0.157,86.977,47.656,6.570,22.471,0.164,0.655,92.657,143.872,10.154,2.645,186.947,3.818,418.728

In [8]:
from fredapi import Fred

# Replace 'your_api_key_here' with your actual FRED API key
fred = Fred(api_key='b73c11e70992c0501f8748360e192763')

# Economic Variables
gdp = fred.get_series('GDP',frequency = 'q')  # Gross Domestic Product (GDP)
employment_rate = fred.get_series('EMRATIO',frequency = 'q')  # Civilian Employment-Population Ratio
industrial_output = fred.get_series('INDPRO',frequency = 'q')  # Industrial Production

In [9]:
# concat the economic variables into a single DataFrame , for date range : 1973-01-01 to 2017-01-01
econ_df = pd.concat([gdp, employment_rate, industrial_output], axis=1)
econ_df.columns = ['GDP', 'Employment Rate', 'Industrial Output']

In [10]:
econ_df = econ_df.resample('MS').mean()
econ_df = econ_df.interpolate(method='linear')

econ_df.reset_index(inplace=True)
econ_df = econ_df.rename(columns={'index': 'Date'})
econ_df

           Date           GDP  Employment Rate  Industrial Output
0    1919-01-01           NaN              NaN           4.678300
1    1919-02-01           NaN              NaN           4.690233
2    1919-03-01           NaN              NaN           4.702167
3    1919-04-01           NaN              NaN           4.714100
4    1919-05-01           NaN              NaN           4.887367
...         ...           ...              ...                ...
1253 2023-06-01  27436.699333        60.366667         103.192167
1254 2023-07-01  27623.543000        60.400000         103.406000
1255 2023-08-01  27623.543000        60.400000         103.406000
1256 2023-09-01  27623.543000        60.400000         103.406000
1257 2023-10-01  27623.543000        60.400000         103.406000

[1258 rows x 4 columns]

In [11]:
# Merge the two DataFrames
merged = pd.merge(merged, econ_df, on='Date')

In [12]:
merged.set_index('Date', inplace=True)

In [13]:
merged

,Coal Production,Natural Gas (Dry) Production,Crude Oil Production,Natural Gas Plant Liquids Production,Total Fossil Fuels Production,Nuclear Electric Power Production,Hydroelectric Power Production,Geothermal Energy Production,Solar Energy Production,Wind Energy Production,Biomass Energy Production,Total Renewable Energy Production,Total Primary Energy Production,Coal Consumption,Natural Gas Consumption (Excluding Supplemental Gaseous Fuels),Petroleum Consumption (Excluding Biofuels),Total Fossil Fuels Consumption,Nuclear Electric Power Consumption,Hydroelectric Power Consumption,Geothermal Energy Consumption,Solar Energy Consumption,Wind Energy Consumption,Biomass Energy Consumption,Total Renewable Energy Consumption,Total Primary Energy Consumption,Aviation Gasoline CO2 Emissions,"Coal, Including Coal Coke Net Imports, CO2 Emissions","Distillate Fuel Oil, Excluding Biodiesel, CO2 Emissions",Hydrocarbon Gas Liquids CO2 Emissions,Jet Fuel CO2 Emissions,Kerosene CO2 Emissions,Lubricants CO2 Emissions,"Motor Gasoline, Excluding Ethanol, CO2 Emissions","Natural Gas, Excluding Supplemental Gaseous Fuels, CO2 Emissions",Other Petroleum Products CO2 Emissions,Petroleum Coke CO2 Emissions,"Petroleum, Excluding Biofuels, CO2 Emissions",Residual Fuel Oil CO2 Emissions,Total Energy CO2 Emissions,GDP,Employment Rate,Industrial Output
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1973-01-01,1.166486,1.908249,1.649833,0.208064,4.932632,0.068103,0.089562,0.00049,Not Available,Not Available,0.129787,0.219839,5.220574,1.166191,2.397308,3.185268,6.747651,0.068103,0.089562,0.00049,Not Available,Not Available,0.129787,0.219839,7.039731,0.428,109.552,55.157,10.463,13.742,5.222,1.037,70.948,125.557,8.754,4.850,218.972,48.370,454.082,1377.490000,57.500000,44.419600
1973-02-01,1.086072,1.922543,1.525783,0.195184,4.729582,0.064634,0.079544,0.000448,Not Available,Not Available,0.117338,0.19733,4.991545,1.050588,2.170646,2.941986,6.163095,0.064634,0.079544,0.000448,Not Available,Not Available,0.117338,0.19733,6.428796,0.431,98.833,51.771,8.848,12.193,4.475,1.025,67.422,113.750,7.674,3.992,202.519,44.686,415.102,1389.622333,57.600000,44.543900
1973-03-01,1.196571,1.86843,1.667094,0.214807,4.946902,0.072494,0.088284,0.000464,Not Available,Not Available,0.129938,0.218686,5.238082,1.046856,2.057315,2.942485,6.044647,0.072494,0.088284,0.000464,Not Available,Not Available,0.129938,0.218686,6.339964,0.459,98.483,44.460,6.687,12.293,2.582,1.105,75.532,107.700,8.659,4.357,201.245,45.111,407.428,1401.754667,57.700000,44.668200
1973-04-01,1.11223,1.777561,1.616791,0.20969,4.716271,0.06407,0.083152,0.000542,Not Available,Not Available,0.125636,0.20933,4.989672,0.998979,1.873535,2.621315,5.493184,0.06407,0.083152,0.000542,Not Available,Not Available,0.125636,0.20933,5.770589,0.446,94.150,33.973,5.793,12.112,2.031,0.979,73.415,97.838,8.230,4.179,176.222,35.063,368.210,1413.887000,57.800000,44.792500
1973-05-01,1.216978,1.859241,1.665377,0.215398,4.956995,0.062111,0.085643,0.000505,Not Available,Not Available,0.129834,0.215982,5.235087,1.014502,1.765309,2.836567,5.613551,0.062111,0.085643,0.000505,Not Available,Not Available,0.129834,0.215982,5.895781,0.549,95.424,35.591,5.489,13.756,1.702,1.156,80.105,92.039,8.688,4.645,188.570,36.889,376.032,1420.537333,57.833333,44.918767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-01,1.051888,3.309225,2.25015,0.688377,7.299641,0.655154,0.07039,0.010065,0.068158,0.151341,0.434435,0.734389,8.689184,0.615143,3.110829,2.990584,6.71453,0.655154,0.07039,0.010065,0.068158,0.151341,0.418218,0.718172,8.096651,0.135,59.007,53.548,8.721,20.393,0.041,0.397,92.491,162.663,8.899,5.650,193.900,3.625,416.503,26979.875000,60.300000,102.706800
2023-04-01,0.949896,3.19418,2.157078,0.683554,6.984709,0.58925,0.061133,0.009906,0.080494,0.146197,0.40114,0.698869,8.272828,0.495403,2.501283,2.887883,5.883058,0.58925,0.061133,0.009906,0.080494,0.146197,0.388387,0.686116,7.16495,0.099,47.665,49.292,7.340,19.841,0.124,0.565,89.617,130.477,9.340,5.703,184.407,2.485,363.452,27063.012000,60.300000,102.764500
2023-05-01,0.975419,3.328101,2.236726,0.706581,7.246826,0.641101,0.095479,0.01006,0.090507,0.109319,0.435031,0.740397,8.628324,0.548899,2.392171,3.025771,5.964029,0.641101,0.095479,0.01006,0.090507,0.109319,0.429438,0.734804,7.348888,0.151,52.595,51.256,6.761,21.243,0.188,0.677,93.490,124.755,9.863,4.266,191.152,3.258,369.434,27249.855667,60.333333,102.978333
2023-06-01,0.954099,3.205094,2.199676,0.699985,7.058854,0.677521,0.066986,0.009549,0.092724,0.093715,0.426737,0.689712,8.426087,0.704001,2.436355,2.97787,6.115871,0.677521,0.066986,0.009549,0.092724,0.093715,0.416358,0.679333,7.47849,0.146,67.181,49.915,6.588,21.316,0.063,0.643,92.105,127.151,9.478,3.377,187.328,3.697,382.562,27436.699333,60.366667,103.192167
2023-07-01,0.993882,3.33754,2.289102,0.71431,7.334834,0.728858,0.073359,0.009941,0.098239,0.0946,0.434776,0.710915,8.774606,0.914884,2.753936,2.993427,6.659002,0.728858,0.073359,0.009941,0.098239,0.0946,0.415928,0.692067,8.093403,0.157,86.977,47.656,6.570,22.471,0.164,0.655,92.657,143.872,10.154,2.645,186.947,3.818,418.728,27623.543000,60.400000,103.406000

In [14]:
merged.to_csv('/Users/pandita/Documents/merged.csv')